typography_spectrum: 0.2507559200748801
color:
  brandStrength: 0.15707016945816576
  lightness: 0.8376340146642178
  saturation: 0.5342072045896202
  rhythmicContrast: 0.7653277344070375
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
layout_spectrum: 0.6411062167026103
author:
  name: Morgan Morey
  email: info@printedobsession.co.uk
  url: printedobsession.co.uk
name: Printed Obsession
title: ...For all those who enjoy 3D printing
