typography_spectrum: 0.19647899828851223
color:
  brandStrength: 0.4749911071266979
  lightness: 0.1389922434464097
  saturation: 0.8869141337927431
  rhythmicContrast: 0.8786848408635706
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.6411062167026103
author:
  name: Morgan Morey
  email: info@printedobsession.co.uk
  url: printedobsession.co.uk
name: Printed Obsession
title: ...For all those who enjoy 3D printing
